
post http://localhost:3006/api/login
Content-Type: application/json

{
    "email": "prueba@email.com",
    "password": "ElGigante2024"
}

###
post http://k8s-default-ingressa-f9307580f5-1616604725.us-east-1.elb.amazonaws.com/api/login
Content-Type: application/json

{
    "email": "prueba@email.com",
    "password": "ElGigante2024"
}