
post http://localhost:3006/api/register
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiUHJ1ZWJhIiwiaWF0IjoxNzIyNzM2NzQxLCJleHAiOjE3MjI3NTExNDF9.dSqhUv1IW6Zpf7qDxCGq7w2tFd5kxTkrvSoQDm0VBGw

{
    "name": "Prueba",
    "email": "prueba2@email.com",
    "password": "ElGigante2024"
}