apiVersion: v1
kind: Service
metadata:
  name: service1
spec:
  type: NodePort
  selector:
    app: appointment
    env: dev
  ports:
    - nodePort: 30000
      port: 7001
      targetPort: 80
      protocol: TCP
