apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-app
  template:
    metadata:
      labels:
        app: gateway-app
    spec:
      containers:
        - name: gateway-ms
          image: 282865065290.dkr.ecr.us-east-1.amazonaws.com/gateway
          imagePullPolicy: Always
          ports:
            - containerPort: 3006
          env:
            - name: PORT
              value: "3006"
            - name: URL_SERVICE_APPOINTMENT_CREATE
              value: "http://appoinment-ms/appointment"
            - name: URL_SERVICE_AUTH_LOGIN
              value: "http://auth/auth/login"
            - name: URL_SERVICE_REGISTER_USER
              value: "http://user/user"
            - name: URL_SERVICE_VALIDATE_TOKEN
              value: "http://auth/auth/validate-token"
